sudo: false
language: node_js
node_js:
  - "stable"
before_install:
  - git config --global user.email "contact@gitbook.com"
  - git config --global user.name "GitBook Team"
script:
  - npm run test
  - npm run lint
